TheRichLifeProject/TheRichLifeProject/Models/WishList.cs
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TheRichLifeProject.Models
{
    public class WishList
    {
        private readonly DatabaseContext _databaseContext;

        public WishList(DatabaseContext databaseContext)
        {
            _databaseContext = databaseContext;
        }

        public static WishList GetList(IServiceProvider services)
        {
            ISession session = services.GetRequiredService<IHttpContextAccessor>()?
                .HttpContext.Session;

            var context = services.GetService<DatabaseContext>();
            string listId = session.GetString("ListId") ?? Guid.NewGuid().ToString();

            session.SetString("ListId", listId);

            return new WishList(context) { WishListId = listId };
        }

        public void AddToList(Product product)
        {
            var wishListItem = _databaseContext.WishListItems.SingleOrDefault(
                s => s.Product.Id == product.Id && s.WishListId == WishListId);

            if (wishListItem == null)
            {
                wishListItem = new WishListItem
                {
                    WishListId = WishListId,
                    Product = product,
                    
                };

                _databaseContext.WishListItems.Add(wishListItem);
            }
            
            _databaseContext.SaveChanges();
        }

        public void RemoveFromList(Product product)
        {
            var wishListItem =
                _databaseContext.WishListItems.SingleOrDefault(
                    s => s.Product.Id == product.Id && s.WishListId == WishListId);

            

            if (wishListItem != null)
            {
                
                 _databaseContext.WishListItems.Remove(wishListItem);
              
            }

            _databaseContext.SaveChanges();

            
        }

        public List<WishListItem> GetWishListItems()
        {
            return WishListItems ??
                (WishListItems =
                _databaseContext.WishListItems.Where(c => c.WishListId == WishListId)
                .Include(s => s.Product).ToList()
                );
        }

        public void ClearList()
        {
            var listItems = _databaseContext
                .WishListItems.Where(cart => cart.WishListId == WishListId);

            _databaseContext.WishListItems.RemoveRange(listItems);

            _databaseContext.SaveChanges();
        }





        public string WishListId { get; set; }

        public List<WishListItem> WishListItems { get; set; }
    }
}

TheRichLifeProject/TheRichLifeProject/Controllers/WishListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TheRichLifeProject.Models;
using TheRichLifeProject.ViewModel;

namespace TheRichLifeProject.Controllers
{
    public class WishListController : Controller
    {
        private readonly WishList _wishList;
        private readonly DatabaseContext _context;
        
        public WishListController(DatabaseContext context, WishList wishList)
        {
            _context = context;
            _wishList = wishList;

        }

        public ViewResult Index()
        {
            var items = _wishList.GetWishListItems();
            _wishList.WishListItems = items;

            var sCVM = new WishListViewModel
            {
                WishList = _wishList,
                
            };

            return View(sCVM);
        }

        public RedirectToActionResult AddToWishList(int productId)
        {
            var selectedProduct = _context.Products.FirstOrDefault(p => p.Id == productId);
            if (selectedProduct != null)
            {
                _wishList.AddToList(selectedProduct);

            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromWishList(int productId)
        {
            var selectedProduct = _context.Products.FirstOrDefault(p => p.Id == productId);
            if (selectedProduct != null)
            {
                _wishList.RemoveFromList(selectedProduct);

            }
            return RedirectToAction("Index");
        }
    }
}

TheRichLifeProject/TheRichLifeProject/Views/WishList/Index.cshtml
@model WishListViewModel

<div class="row checkoutForm">
    <h2>Your wishlist</h2>
    <h4>Here are the products in your wishlist.</h4>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Product</th>
                <th class="text-right">Price</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var line in Model.WishList.WishListItems)
            {
            <tr>
                <td class="text-left"><a asp-controller="Product" asp-action="Detail" asp-route-id="@line.Product.Id">@line.Product.ProductName</a></td>
                <td class="text-right">@line.Product.Price.ToString("c")</td>
                <td class="text-center"><a class="glyphicon glyphicon-remove text-danger remove" asp-controller="WishList" asp-action="RemoveFromWishList" asp-route-productId="@line.Product.Id"></a></td>
                <td class="text-center"><a class="btn btn-success" asp-controller="Cart" asp-action="Add" asp-route-productId="@line.Product.Id">Add to cart</a></td>
            </tr>
            }
        </tbody>
        <tfoot>
            <tr></tr>
        </tfoot>
    </table>
</div>